[postgres]
host = "ep-divine-union-a1xc6yu9-pooler.ap-southeast-1.aws.neon.tech"
port = "5432"
dbname = "neondb"
user = "neondb_owner"
password = "npg_1HEcf0QlbJux"  # Make sure this matches exactly from Neon dashboard
sslmode = "require"  # Add this line
